#![crate_type = "lib"]
#![crate_name = "jsonless"]
#![recursion_limit = "1000"]

use std::collections::HashMap;
use serde_json::{Value, Map};

pub struct Options {
    pub symbol: char,
    pub signature: Option<Value>
}

impl Options {
    fn new (symbol: char, signature: Option<Value>) -> Options {
        return Options {symbol, signature}
    }
}

#[no_mangle]
pub extern "C" fn encode(data: &Value) -> Value {
    let options = Options {
        symbol: '$',
        signature: None
    };
    encode_with_options(&data, options)
}

#[no_mangle]
pub extern "C" fn encode_with_options(json: &Value, options: Options) -> Value {
    let all_props_map = HashMap::new();
    let all_prop_groups: Vec<Vec<u16>> = Vec::new();

    let (mut encoded, all_prop_groups_returned, all_props_map_returned) =
        encode_single(&json, all_prop_groups, options.symbol, all_props_map);

    let mut vec: Vec<String> = vec![String::new(); all_props_map_returned.len()];
    for (prop, index) in all_props_map_returned {
        vec[index as usize] = prop;
    }
    let s = vec.join(&*options.symbol.to_string());
    let mut signature = vec![Value::String(s)];
    for prop_group in all_prop_groups_returned {

        let prop_group_str: Vec<String> = prop_group.iter().map(|&x| x.to_string()).collect();
        signature.push(Value::String(prop_group_str.join(&*options.symbol.to_string())));
    }
    encoded.as_array_mut().unwrap().push(Value::Array(signature));
    encoded
}

fn encode_single(json: &Value, mut all_prop_groups: Vec<Vec<u16>>, symbol: char, mut all_props_map: HashMap<String, isize>) -> (Value, Vec<Vec<u16>>, HashMap<String, isize>) {
    let mut my_prop_group: Vec<u16> = Vec::new();
    let mut arr: Vec<Value> = Vec::new();
    if json.is_object() {
        let obj = json.as_object().expect("Expected object");
        for (prop, value) in obj {
            let mut index = index_of(prop, &all_props_map);
            if index == -1 {
                index = all_props_map.len() as isize;
                all_props_map.insert(prop.to_string(), index);
            }
            my_prop_group.push(index as u16);
            let (encoded_value, all_prop_groups_returned, all_props_map_returned) =
                encode_single(&value, all_prop_groups, symbol, all_props_map);
            all_prop_groups = all_prop_groups_returned;
            all_props_map = all_props_map_returned;
            arr.push(encoded_value);
        }

        let mut index = index_of_group(&my_prop_group, &all_prop_groups);
        if index == -1 {
            index = all_prop_groups.len() as i32;
            all_prop_groups.push(my_prop_group);
        }
        arr.push(Value::String(format!("{}{}", symbol, index)));
    } else if json.is_array() {
        let arr_vec = json.as_array().expect("Expected array");
        for value in arr_vec {
            let (encoded_value, all_prop_groups_returned, all_props_map_returned) =
                encode_single(&value, all_prop_groups, symbol, all_props_map);
            all_prop_groups = all_prop_groups_returned;
            all_props_map = all_props_map_returned;
            arr.push(encoded_value);
        }
    } else {
        return (json.clone(), all_prop_groups, all_props_map);
    }
    (Value::Array(arr), all_prop_groups, all_props_map)
}

fn index_of(prop: &String, all_props_map: &HashMap<String, isize>) -> isize {
    return match all_props_map.get(prop){
        None => {
            -1
        },
        Some(i) => i.to_owned()
    };
}

fn index_of_group(my_prop_group: &Vec<u16>, all_prop_groups: &Vec<Vec<u16>>) -> i32 {
    for i in 0..all_prop_groups.len() {
        let prop_group = &all_prop_groups[i];
        if my_prop_group.len() != prop_group.len() {
            continue;
        }
        let mut broken = false;
        for y in 0..my_prop_group.len() {
            if my_prop_group.get(y) != prop_group.get(y) {
                broken = true;
                break;
            }
        }
        if !broken {
            return i as i32;
        }
    }
    -1
}

#[no_mangle]
pub extern "C" fn without_signature(data: &Value) -> Value {
    let mut cloned = data.clone();
    let arr = cloned.as_array_mut().unwrap();
    arr.remove(arr.len()-1);
    cloned
}

#[no_mangle]
pub extern "C" fn get_signature(data: &Value) -> Value {
    let arr = data.as_array().unwrap();
    arr.last().unwrap().clone()
}

#[no_mangle]
pub extern "C" fn decode(data: &Value) -> Value {
    let options = Options {
        symbol: '$',
        signature: None
    };
    decode_with_options(&data, options)
}

#[no_mangle]
pub extern "C" fn decode_with_options(json: &Value, options: Options) -> Value {
    let arr = json.as_array().unwrap();
    let len;
    let signature: Value = match options.signature {
        None => {
            len = arr.len() - 1;
            arr.get(len).unwrap().to_owned()
        },
        Some(i) => {
            len = arr.len();
            i
        }
    };

    let signature_arr = signature.as_array().unwrap();

    let all_props_str: Vec<&str> = signature_arr.get(0).unwrap()
        .as_str().unwrap()
        .split(&*options.symbol.to_string()).collect();

    let all_props: Vec<String> = all_props_str.iter()
        .map(|&s| s.to_owned())
        .collect();

    let mut all_prop_groups: Vec<Vec<usize>> = Vec::new();
    for i in 1..signature_arr.len() {

        let prop_group_str: Vec<&str> = signature_arr.get(i).unwrap()
            .as_str().unwrap()
            .split(&*options.symbol.to_string()).collect();

        let prop_group: Vec<usize> = prop_group_str.iter()
            .map(|&r| r.parse().unwrap())
            .collect();
        all_prop_groups.push(prop_group);
    }

    let decoded = decode_single(&json, &len, &all_props, &all_prop_groups, options.symbol);

    decoded
}

fn decode_single(json: &Value, len: &usize, all_props: &Vec<String>, all_prop_groups: &Vec<Vec<usize>>, symbol: char) -> Value {
    let arr = json.as_array().unwrap();
    let last = arr.get(len - 1).unwrap();
    if last.is_string() && last.as_str().unwrap().starts_with(symbol) {
        let mut map = Map::new();
        let group_index_with_sign = last.as_str().unwrap().to_string();
        let group_index: usize  = *&group_index_with_sign[1..group_index_with_sign.len()].parse().unwrap();
        let prop_indexes = all_prop_groups.get(group_index).unwrap();
        for i in 0..len - 1 {
            let value = arr.get(i).unwrap();
            let decoded_value = if value.is_array() {
                let arr = value.as_array().unwrap();
                decode_single(&value, &arr.len(), &all_props, &all_prop_groups, symbol)
            } else {
                value.clone()
            };
            let prop_index: usize = *prop_indexes.get(i).unwrap();
            let key = all_props.get(prop_index).unwrap();
            map.insert(key.to_string(), decoded_value);
        }
        Value::Object(map)
    } else {
        let mut decoded_arr = vec![];
        for i in 0..*len {
            let value = arr.get(i).unwrap();
            let decoded_value = if value.is_array() {
                decode_single(&value, &value.as_array().unwrap().len(), &all_props, &all_prop_groups, symbol)
            } else {
                value.clone()
            };
            decoded_arr.push(decoded_value)
        }
        return Value::Array(decoded_arr);
    }
}

#[cfg(test)]
mod tests {
    use std::time::Instant;
    use crate::{decode, encode, get_signature, without_signature};
    use serde_json::json;

    #[test]
    fn encode_object1() {
        let object1 = json!({
            "gid": "0022300759",
            "htm": {
                "Assists": 7,
                "AssistsTurnoverRatio": 2.33333333333333,
                "BlocksReceived": 1
            },
            "players": {
                "201143": {
                    "Assists": [1,2,3,4],
                    "AssistsTurnoverRatio": 0,
                    "BlocksReceived": 1
                },
                "201567": {
                    "Assists": 2,
                    "AssistsTurnoverRatio": 0,
                    "BlocksReceived": 3
                }
            }
        });

        let object1_encoded = json!([
            "0022300759",
            [7,2.33333333333333,1,"$0"],
            [
                [[1,2,3,4],0,1,"$0"],
                [2,0,3,"$0"],
                "$1"
            ],
            "$2",
            [
            "gid$htm$Assists$AssistsTurnoverRatio$BlocksReceived$players$201143$201567",
                "2$3$4",
                "6$7",
                "0$1$5"
            ]
        ]);

        assert_eq!(&encode(&object1), &object1_encoded);
    }

    #[test]
    fn object1_encoded_without_signature() {
        let object1_encoded = json!([
            "0022300759",
            [7,2.33333333333333,1,"$0"],
            [
                [[1,2,3,4],0,1,"$0"],
                [2,0,3,"$0"],
                "$1"
            ],
            "$2",
            [
            "gid$htm$Assists$AssistsTurnoverRatio$BlocksReceived$players$201143$201567",
                "2$3$4",
                "6$7",
                "0$1$5"
            ]
        ]);

        let object1_encoded_without_signature = json!([
            "0022300759",
            [7,2.33333333333333,1,"$0"],
            [
                [[1,2,3,4],0,1,"$0"],
                [2,0,3,"$0"],
                "$1"
            ],
            "$2"
        ]);

        assert_eq!(&without_signature(&object1_encoded), &object1_encoded_without_signature);
    }

    #[test]
    fn get_signature_of_object1_encoded() {
        let object1_encoded = json!([
            "0022300759",
            [7,2.33333333333333,1,"$0"],
            [
                [[1,2,3,4],0,1,"$0"],
                [2,0,3,"$0"],
                "$1"
            ],
            "$2",
            [
            "gid$htm$Assists$AssistsTurnoverRatio$BlocksReceived$players$201143$201567",
                "2$3$4",
                "6$7",
                "0$1$5"
            ]
        ]);

        let signature = json!([
            "gid$htm$Assists$AssistsTurnoverRatio$BlocksReceived$players$201143$201567",
                "2$3$4",
                "6$7",
                "0$1$5"
            ]);

        assert_eq!(&get_signature(&object1_encoded), &signature);
    }

    #[test]
    fn encode_object2() {
        let object2 = json!([
                "player1",
                {
                    "gid":"0022300759",
                    "htm": "SAN"
                }
            ]);

            let object2_encoded = json!([
            "player1",
            ["0022300759", "SAN", "$0"],
            ["gid$htm","0$1"]
        ]);

        assert_eq!(&encode(&object2), &object2_encoded);
    }

    #[test]
    fn decode_object1() {
        let object1 = json!({
            "gid": "0022300759",
            "htm": {
                "Assists": 7,
                "AssistsTurnoverRatio": 2.33333333333333,
                "BlocksReceived": 1
            },
            "players": {
                "201143": {
                    "Assists": [1,2,3,4],
                    "AssistsTurnoverRatio": 0,
                    "BlocksReceived": 1
                },
                "201567": {
                    "Assists": 2,
                    "AssistsTurnoverRatio": 0,
                    "BlocksReceived": 3
                }
            }
        });

        let object1_encoded = json!([
            "0022300759",
            [7,2.33333333333333,1,"$0"],
            [
                [[1,2,3,4],0,1,"$0"],
                [2,0,3,"$0"],
                "$1"
            ],
            "$2",
            [
            "gid$htm$Assists$AssistsTurnoverRatio$BlocksReceived$players$201143$201567",
                "2$3$4",
                "6$7",
                "0$1$5"
            ]
        ]);

        assert_eq!(&decode(&object1_encoded), &object1);
    }

    #[test]
    fn decode_object2() {
        let object2 = json!([
                "player1",
                {
                    "gid":"0022300759",
                    "htm": "SAN"
                }
            ]);

        let object2_encoded = json!([
            "player1",
            ["0022300759", "SAN", "$0"],
            ["gid$htm","0$1"]
        ]);

        assert_eq!(&decode(&object2_encoded), &object2);
    }

    #[test]
    fn encode_object_perf() {
        let object = json!({
  "htm": {
    "Assists": 30,
    "AssistsTurnoverRatio": 2.72727272727273,
    "BenchPoints": 21,
    "BiggestLead": 24,
    "BiggestLeadScore": "67-91",
    "BiggestScoringRun": 16,
    "BiggestScoringRunScore": "66-88",
    "Blocks": 9,
    "BlocksReceived": 5,
    "DefensivePointsPerPossession": 1.0894716544543,
    "DefensiveRating": 108.94716544543,
    "Efficiency": "",
    "FastBreakPointsAttempted": 10,
    "FastBreakPointsMade": 6,
    "FastBreakPointsPercentage": 60,
    "FieldGoalsAttempted": 85,
    "FieldGoalsEffectiveAdjusted": 0.61764705882353,
    "FieldGoalsMade": 46,
    "FieldGoalsPercentage": 54.1176470588235,
    "FoulsDrawn": 22,
    "FoulsOffensive": 1,
    "FoulsPersonal": 17,
    "FoulsTeam": 16,
    "FoulsTeamTechnical": 0,
    "FoulsTechnical": 0,
    "FreeThrowsAttempted": 27,
    "FreeThrowsMade": 22,
    "FreeThrowsPercentage": 81.4814814814815,
    "LeadChanges": 5,
    "Minutes": "PT240M00.00S",
    "MinutesCalculated": "PT240M",
    "OffensivePointsPerPossession": 1.23444790046656,
    "OffensiveRating": 123.444790046656,
    "OppPointsFromTurnovers": 14,
    "Pace": "",
    "Points": 127,
    "PointsAgainst": 113,
    "PointsFastBreak": 14,
    "PointsFromTurnovers": 30,
    "PointsInThePaint": 54,
    "PointsInThePaintAttempted": 46,
    "PointsInThePaintMade": 27,
    "PointsInThePaintPercentage": 58.695652173913,
    "PointsSecondChance": 9,
    "Possessions": 102.88,
    "PossessionsOpponent": 103.72,
    "ReboundsDefensive": 31,
    "ReboundsOffensive": 5,
    "ReboundsPersonal": 36,
    "ReboundsTeam": 11,
    "ReboundsTeamDefensive": 2,
    "ReboundsTeamOffensive": 9,
    "ReboundsTotal": 47,
    "SecondChancePointsAttempted": 4,
    "SecondChancePointsMade": 2,
    "SecondChancePointsPercentage": 50,
    "Steals": 8,
    "ThreePointersAttempted": 27,
    "ThreePointersMade": 13,
    "ThreePointersPercentage": 48.1481481481481,
    "TimeLeading": "PT44M02.98S",
    "TimesTied": 4,
    "TransitionDefence": "",
    "TransitionOffence": "",
    "TrueShootingAttempts": 96.88,
    "TrueShootingPercentage": 65.5450041288192,
    "Turnovers": 9,
    "TurnoversTeam": 2,
    "TurnoversTotal": 11,
    "TwoPointersAttempted": 58,
    "TwoPointersMade": 33,
    "TwoPointersPercentage": 56.8965517241379,
    "challengesRemaining": 1,
    "fouls": 4,
    "foulsToGive": 0,
    "isBonus": true,
    "toRemaining": 2
  },
  "players": {
    "201580": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 14,
      "pid": 201580,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "202330": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 16,
      "pid": 202330,
      "status": "INACTIVE",
      "tid": 1610612760
    },
    "202687": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 15,
      "pid": 202687,
      "status": "INACTIVE",
      "tid": 1610612760
    },
    "203084": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": 130.231241858876,
      "Efficiency": "",
      "EfficiencyGameScore": 9.8,
      "FastBreakPointsAttempted": 1,
      "FastBreakPointsMade": 1,
      "FastBreakPointsPercentage": 100,
      "FieldGoalsAttempted": 7,
      "FieldGoalsEffectivePercentage": 64.2857142857143,
      "FieldGoalsMade": 4,
      "FieldGoalsPercentage": 57.1428571428571,
      "FoulsDrawn": 3,
      "FoulsOffensive": 0,
      "FoulsPersonal": 3,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 5,
      "FreeThrowsMade": 5,
      "FreeThrowsPercentage": 100,
      "Minus": 67,
      "Minutes": "PT21M24.00S",
      "MinutesCalculated": "PT21M",
      "OffensiveRating": 158.433285776371,
      "Plus": 40,
      "PlusMinusPoints": -27,
      "Points": 14,
      "PointsFastBreak": 2,
      "PointsInThePaint": 6,
      "PointsInThePaintAttempted": 3,
      "PointsInThePaintMade": 3,
      "PointsInThePaintPercentage": 100,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 1,
      "ReboundsDefensivePercentage": 6.40854472630173,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 2.9513034923758,
      "ReboundsTotal": 1,
      "SecondChancePointsAttempted": 1,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 4,
      "ThreePointersMade": 1,
      "ThreePointersPercentage": 25,
      "TrueShootingAttempts": 9.2,
      "TrueShootingPercentage": 76.0869565217391,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 3,
      "TwoPointersMade": 3,
      "TwoPointersPercentage": 100,
      "hasPlayed": true,
      "isOnCourt": false,
      "isStarter": true,
      "order": 2,
      "pid": 203084,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "203458": {
      "Assists": 1,
      "AssistsTurnoverRatio": 1,
      "Blocks": 0,
      "BlocksReceived": 1,
      "DefensiveRating": 87.6153021934814,
      "Efficiency": "",
      "EfficiencyGameScore": -0.1,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 1,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 1,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 2,
      "Minutes": "PT02M44.00S",
      "MinutesCalculated": "PT03M",
      "OffensiveRating": 32.1775365922543,
      "Plus": 5,
      "PlusMinusPoints": 3,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 1,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 1,
      "ReboundsDefensivePercentage": 50.1742160278746,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 23.1065468549422,
      "ReboundsTotal": 1,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 1,
      "StealsPercentage": 17.0693775366992,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 1,
      "TrueShootingPercentage": 0,
      "Turnovers": 1,
      "TurnoversPercentage": 50,
      "TwoPointersAttempted": 1,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": true,
      "isOnCourt": false,
      "isStarter": false,
      "order": 10,
      "pid": 203458,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1626168": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 1,
      "BlocksReceived": 0,
      "DefensiveRating": 121.345034174828,
      "Efficiency": "",
      "EfficiencyGameScore": 1,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 2,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 1,
      "FoulsOffensive": 1,
      "FoulsPersonal": 2,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 2,
      "FreeThrowsMade": 1,
      "FreeThrowsPercentage": 50,
      "Minus": 59,
      "Minutes": "PT24M18.00S",
      "MinutesCalculated": "PT24M",
      "OffensiveRating": 46.2276699927833,
      "Plus": 65,
      "PlusMinusPoints": 6,
      "Points": 1,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 4,
      "ReboundsDefensivePercentage": 22.5749559082892,
      "ReboundsOffensive": 1,
      "ReboundsOffensivePercentage": 4.81782595603734,
      "ReboundsPercentage": 12.9954515919428,
      "ReboundsTotal": 5,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 1,
      "StealsPercentage": 1.92001228807864,
      "ThreePointersAttempted": 2,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 2.88,
      "TrueShootingPercentage": 17.3611111111111,
      "Turnovers": 1,
      "TurnoversPercentage": 25.7731958762887,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": true,
      "isOnCourt": false,
      "isStarter": false,
      "order": 8,
      "pid": 1626168,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1627734": {
      "Assists": 14,
      "AssistsTurnoverRatio": 2.8,
      "Blocks": 0,
      "BlocksReceived": 2,
      "DefensiveRating": 126.271907718854,
      "Efficiency": "",
      "EfficiencyGameScore": 23.9,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 14,
      "FieldGoalsEffectivePercentage": 67.8571428571429,
      "FieldGoalsMade": 9,
      "FieldGoalsPercentage": 64.2857142857143,
      "FoulsDrawn": 4,
      "FoulsOffensive": 2,
      "FoulsPersonal": 3,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 3,
      "FreeThrowsMade": 2,
      "FreeThrowsPercentage": 66.6666666666666,
      "Minus": 113,
      "Minutes": "PT41M32.00S",
      "MinutesCalculated": "PT42M",
      "OffensiveRating": 131.081489547792,
      "Plus": 106,
      "PlusMinusPoints": -7,
      "Points": 21,
      "PointsFastBreak": 0,
      "PointsInThePaint": 16,
      "PointsInThePaintAttempted": 12,
      "PointsInThePaintMade": 8,
      "PointsInThePaintPercentage": 66.6666666666666,
      "PointsSecondChance": 6,
      "ReboundsDefensive": 7,
      "ReboundsDefensivePercentage": 23.1139646869984,
      "ReboundsOffensive": 4,
      "ReboundsOffensivePercentage": 11.2751047253651,
      "ReboundsPercentage": 16.7272112866436,
      "ReboundsTotal": 11,
      "SecondChancePointsAttempted": 3,
      "SecondChancePointsMade": 3,
      "SecondChancePointsPercentage": 100,
      "Steals": 1,
      "StealsPercentage": 1.12334587320171,
      "ThreePointersAttempted": 2,
      "ThreePointersMade": 1,
      "ThreePointersPercentage": 50,
      "TrueShootingAttempts": 15.32,
      "TrueShootingPercentage": 68.5378590078329,
      "Turnovers": 5,
      "TurnoversPercentage": 24.6062992125984,
      "TwoPointersAttempted": 12,
      "TwoPointersMade": 8,
      "TwoPointersPercentage": 66.6666666666666,
      "hasPlayed": true,
      "isOnCourt": true,
      "isStarter": true,
      "order": 3,
      "pid": 1627734,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1628368": {
      "Assists": 5,
      "AssistsTurnoverRatio": 1.66666666666667,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": 130.525283543332,
      "Efficiency": "",
      "EfficiencyGameScore": 4.3,
      "FastBreakPointsAttempted": 2,
      "FastBreakPointsMade": 2,
      "FastBreakPointsPercentage": 100,
      "FieldGoalsAttempted": 17,
      "FieldGoalsEffectivePercentage": 41.1764705882353,
      "FieldGoalsMade": 6,
      "FieldGoalsPercentage": 35.2941176470588,
      "FoulsDrawn": 5,
      "FoulsOffensive": 0,
      "FoulsPersonal": 3,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 3,
      "FreeThrowsMade": 1,
      "FreeThrowsPercentage": 33.3333333333333,
      "Minus": 96,
      "Minutes": "PT32M45.07S",
      "MinutesCalculated": "PT33M",
      "OffensiveRating": 84.1074639001303,
      "Plus": 69,
      "PlusMinusPoints": -27,
      "Points": 15,
      "PointsFastBreak": 5,
      "PointsInThePaint": 6,
      "PointsInThePaintAttempted": 6,
      "PointsInThePaintMade": 3,
      "PointsInThePaintPercentage": 50,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 1,
      "ReboundsDefensivePercentage": 4.18741898689178,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 1.92841663870016,
      "ReboundsTotal": 1,
      "SecondChancePointsAttempted": 1,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 8,
      "ThreePointersMade": 2,
      "ThreePointersPercentage": 25,
      "TrueShootingAttempts": 18.32,
      "TrueShootingPercentage": 40.938864628821,
      "Turnovers": 3,
      "TurnoversPercentage": 14.0712945590994,
      "TwoPointersAttempted": 9,
      "TwoPointersMade": 4,
      "TwoPointersPercentage": 44.4444444444444,
      "hasPlayed": true,
      "isOnCourt": true,
      "isStarter": true,
      "order": 5,
      "pid": 1628368,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1628370": {
      "Assists": 5,
      "AssistsTurnoverRatio": 1.25,
      "Blocks": 1,
      "BlocksReceived": 3,
      "DefensiveRating": 126.908011756331,
      "Efficiency": "",
      "EfficiencyGameScore": 16.6,
      "FastBreakPointsAttempted": 2,
      "FastBreakPointsMade": 2,
      "FastBreakPointsPercentage": 100,
      "FieldGoalsAttempted": 20,
      "FieldGoalsEffectivePercentage": 65,
      "FieldGoalsMade": 10,
      "FieldGoalsPercentage": 50,
      "FoulsDrawn": 2,
      "FoulsOffensive": 0,
      "FoulsPersonal": 3,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 69,
      "Minutes": "PT29M04.00S",
      "MinutesCalculated": "PT29M",
      "OffensiveRating": 109.874366537612,
      "Plus": 65,
      "PlusMinusPoints": -4,
      "Points": 26,
      "PointsFastBreak": 5,
      "PointsInThePaint": 4,
      "PointsInThePaintAttempted": 8,
      "PointsInThePaintMade": 2,
      "PointsInThePaintPercentage": 25,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 3,
      "ReboundsDefensivePercentage": 14.1546526867628,
      "ReboundsOffensive": 1,
      "ReboundsOffensivePercentage": 4.02774669948534,
      "ReboundsPercentage": 8.69145340415258,
      "ReboundsTotal": 4,
      "SecondChancePointsAttempted": 3,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 10,
      "ThreePointersMade": 6,
      "ThreePointersPercentage": 60,
      "TrueShootingAttempts": 20,
      "TrueShootingPercentage": 65,
      "Turnovers": 4,
      "TurnoversPercentage": 16.6666666666667,
      "TwoPointersAttempted": 10,
      "TwoPointersMade": 4,
      "TwoPointersPercentage": 40,
      "hasPlayed": true,
      "isOnCourt": true,
      "isStarter": false,
      "order": 7,
      "pid": 1628370,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1628426": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 18,
      "pid": 1628426,
      "status": "INACTIVE",
      "tid": 1610612758
    },
    "1628983": {
      "Assists": 7,
      "AssistsTurnoverRatio": 7,
      "Blocks": 2,
      "BlocksReceived": 2,
      "DefensiveRating": 111.841030085994,
      "Efficiency": "",
      "EfficiencyGameScore": 31.4,
      "FastBreakPointsAttempted": 5,
      "FastBreakPointsMade": 4,
      "FastBreakPointsPercentage": 80,
      "FieldGoalsAttempted": 26,
      "FieldGoalsEffectivePercentage": 63.4615384615385,
      "FieldGoalsMade": 15,
      "FieldGoalsPercentage": 57.6923076923077,
      "FoulsDrawn": 9,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 9,
      "FreeThrowsMade": 5,
      "FreeThrowsPercentage": 55.5555555555556,
      "Minus": 87,
      "Minutes": "PT38M48.00S",
      "MinutesCalculated": "PT39M",
      "OffensiveRating": 127.793044516212,
      "Plus": 103,
      "PlusMinusPoints": 16,
      "Points": 38,
      "PointsFastBreak": 8,
      "PointsInThePaint": 18,
      "PointsInThePaintAttempted": 16,
      "PointsInThePaintMade": 9,
      "PointsInThePaintPercentage": 56.25,
      "PointsSecondChance": 4,
      "ReboundsDefensive": 3,
      "ReboundsDefensivePercentage": 9.05204928337943,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 4.88334237655996,
      "ReboundsTotal": 3,
      "SecondChancePointsAttempted": 1,
      "SecondChancePointsMade": 1,
      "SecondChancePointsPercentage": 100,
      "Steals": 1,
      "StealsPercentage": 1.19274334946187,
      "ThreePointersAttempted": 4,
      "ThreePointersMade": 3,
      "ThreePointersPercentage": 75,
      "TrueShootingAttempts": 29.96,
      "TrueShootingPercentage": 63.4178905206942,
      "Turnovers": 1,
      "TurnoversPercentage": 3.22997416020672,
      "TwoPointersAttempted": 22,
      "TwoPointersMade": 12,
      "TwoPointersPercentage": 54.5454545454545,
      "hasPlayed": true,
      "isOnCourt": true,
      "isStarter": true,
      "order": 5,
      "pid": 1628983,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1628989": {
      "Assists": 1,
      "AssistsTurnoverRatio": 0.5,
      "Blocks": 0,
      "BlocksReceived": 2,
      "DefensiveRating": 130.328452336047,
      "Efficiency": "",
      "EfficiencyGameScore": -0.4,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 7,
      "FieldGoalsEffectivePercentage": 28.5714285714286,
      "FieldGoalsMade": 2,
      "FieldGoalsPercentage": 28.5714285714286,
      "FoulsDrawn": 1,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 55,
      "Minutes": "PT17M10.00S",
      "MinutesCalculated": "PT17M",
      "OffensiveRating": 59.2493189755125,
      "Plus": 35,
      "PlusMinusPoints": -20,
      "Points": 4,
      "PointsFastBreak": 0,
      "PointsInThePaint": 2,
      "PointsInThePaintAttempted": 3,
      "PointsInThePaintMade": 1,
      "PointsInThePaintPercentage": 33.3333333333333,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 1,
      "ReboundsDefensivePercentage": 7.98890429958391,
      "ReboundsOffensive": 1,
      "ReboundsOffensivePercentage": 6.81979635330334,
      "ReboundsPercentage": 7.35820132856413,
      "ReboundsTotal": 2,
      "SecondChancePointsAttempted": 2,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 3,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 7,
      "TrueShootingPercentage": 28.5714285714286,
      "Turnovers": 2,
      "TurnoversPercentage": 22.2222222222222,
      "TwoPointersAttempted": 4,
      "TwoPointersMade": 2,
      "TwoPointersPercentage": 50,
      "hasPlayed": true,
      "isOnCourt": false,
      "isStarter": true,
      "order": 4,
      "pid": 1628989,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1629026": {
      "Assists": 1,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": 117.285644468858,
      "Efficiency": "",
      "EfficiencyGameScore": 5.7,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 3,
      "FieldGoalsEffectivePercentage": 100,
      "FieldGoalsMade": 2,
      "FieldGoalsPercentage": 66.6666666666666,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 30,
      "Minutes": "PT10M45.03S",
      "MinutesCalculated": "PT11M",
      "OffensiveRating": 184.481275739935,
      "Plus": 28,
      "PlusMinusPoints": -2,
      "Points": 6,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 1,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 1,
      "ReboundsDefensivePercentage": 10.8900209973217,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 5.87487974855515,
      "ReboundsTotal": 1,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 2,
      "ThreePointersMade": 2,
      "ThreePointersPercentage": 100,
      "TrueShootingAttempts": 3,
      "TrueShootingPercentage": 100,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 1,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": true,
      "isOnCourt": false,
      "isStarter": false,
      "order": 11,
      "pid": 1629026,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1629652": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 1,
      "BlocksReceived": 0,
      "DefensiveRating": 101.962010683542,
      "Efficiency": "",
      "EfficiencyGameScore": 16.7,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 9,
      "FieldGoalsEffectivePercentage": 72.2222222222222,
      "FieldGoalsMade": 5,
      "FieldGoalsPercentage": 55.5555555555556,
      "FoulsDrawn": 4,
      "FoulsOffensive": 0,
      "FoulsPersonal": 3,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 4,
      "FreeThrowsMade": 4,
      "FreeThrowsPercentage": 100,
      "Minus": 65,
      "Minutes": "PT32M45.07S",
      "MinutesCalculated": "PT33M",
      "OffensiveRating": 132.197525782623,
      "Plus": 96,
      "PlusMinusPoints": 31,
      "Points": 17,
      "PointsFastBreak": 0,
      "PointsInThePaint": 2,
      "PointsInThePaintAttempted": 2,
      "PointsInThePaintMade": 1,
      "PointsInThePaintPercentage": 50,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 7,
      "ReboundsDefensivePercentage": 25.0223817509387,
      "ReboundsOffensive": 2,
      "ReboundsOffensivePercentage": 8.37483797378356,
      "ReboundsPercentage": 17.3557497483015,
      "ReboundsTotal": 9,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 3,
      "StealsPercentage": 4.23909558063668,
      "ThreePointersAttempted": 5,
      "ThreePointersMade": 3,
      "ThreePointersPercentage": 60,
      "TrueShootingAttempts": 10.76,
      "TrueShootingPercentage": 78.996282527881,
      "Turnovers": 2,
      "TurnoversPercentage": 15.6739811912226,
      "TwoPointersAttempted": 4,
      "TwoPointersMade": 2,
      "TwoPointersPercentage": 50,
      "hasPlayed": true,
      "isOnCourt": true,
      "isStarter": true,
      "order": 1,
      "pid": 1629652,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1630197": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 12,
      "pid": 1630197,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1630198": {
      "Assists": 2,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": 109.481696712338,
      "Efficiency": "",
      "EfficiencyGameScore": 5.6,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 1,
      "FieldGoalsEffectivePercentage": 150,
      "FieldGoalsMade": 1,
      "FieldGoalsPercentage": 100,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 2,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 47,
      "Minutes": "PT16M20.97S",
      "MinutesCalculated": "PT16M",
      "OffensiveRating": 250.708848069555,
      "Plus": 36,
      "PlusMinusPoints": -11,
      "Points": 3,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 2,
      "ReboundsDefensivePercentage": 14.3213151144325,
      "ReboundsOffensive": 1,
      "ReboundsOffensivePercentage": 8.38819885273905,
      "ReboundsPercentage": 11.5889589412842,
      "ReboundsTotal": 3,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 1,
      "StealsPercentage": 2.83057230857951,
      "ThreePointersAttempted": 1,
      "ThreePointersMade": 1,
      "ThreePointersPercentage": 100,
      "TrueShootingAttempts": 1,
      "TrueShootingPercentage": 150,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": true,
      "isOnCourt": false,
      "isStarter": false,
      "order": 8,
      "pid": 1630198,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1630222": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 16,
      "pid": 1630222,
      "status": "INACTIVE",
      "tid": 1610612758
    },
    "1630259": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 15,
      "pid": 1630259,
      "status": "INACTIVE",
      "tid": 1610612758
    },
    "1630322": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 14,
      "pid": 1630322,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1630537": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 11,
      "pid": 1630537,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1630556": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 12,
      "pid": 1630556,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1630558": {
      "Assists": 2,
      "AssistsTurnoverRatio": 2,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": 123.700820903438,
      "Efficiency": "",
      "EfficiencyGameScore": 14,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 6,
      "FieldGoalsEffectivePercentage": 116.666666666667,
      "FieldGoalsMade": 5,
      "FieldGoalsPercentage": 83.3333333333334,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 2,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 40,
      "Minutes": "PT19M50.00S",
      "MinutesCalculated": "PT20M",
      "OffensiveRating": 174.514609938413,
      "Plus": 63,
      "PlusMinusPoints": 23,
      "Points": 14,
      "PointsFastBreak": 0,
      "PointsInThePaint": 2,
      "PointsInThePaintAttempted": 2,
      "PointsInThePaintMade": 1,
      "PointsInThePaintPercentage": 50,
      "PointsSecondChance": 3,
      "ReboundsDefensive": 3,
      "ReboundsDefensivePercentage": 20.7442977190876,
      "ReboundsOffensive": 1,
      "ReboundsOffensivePercentage": 5.90284894445583,
      "ReboundsPercentage": 12.7377266696152,
      "ReboundsTotal": 4,
      "SecondChancePointsAttempted": 1,
      "SecondChancePointsMade": 1,
      "SecondChancePointsPercentage": 100,
      "Steals": 1,
      "StealsPercentage": 2.35241841682241,
      "ThreePointersAttempted": 4,
      "ThreePointersMade": 4,
      "ThreePointersPercentage": 100,
      "TrueShootingAttempts": 6,
      "TrueShootingPercentage": 116.666666666667,
      "Turnovers": 1,
      "TurnoversPercentage": 14.2857142857143,
      "TwoPointersAttempted": 2,
      "TwoPointersMade": 1,
      "TwoPointersPercentage": 50,
      "hasPlayed": true,
      "isOnCourt": false,
      "isStarter": false,
      "order": 6,
      "pid": 1630558,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1630581": {
      "Assists": 4,
      "AssistsTurnoverRatio": 0,
      "Blocks": 1,
      "BlocksReceived": 1,
      "DefensiveRating": 109.581385678188,
      "Efficiency": "",
      "EfficiencyGameScore": 5.4,
      "FastBreakPointsAttempted": 1,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 6,
      "FieldGoalsEffectivePercentage": 41.6666666666667,
      "FieldGoalsMade": 2,
      "FieldGoalsPercentage": 33.3333333333333,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 3,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 35,
      "Minutes": "PT20M04.93S",
      "MinutesCalculated": "PT20M",
      "OffensiveRating": 111.114629093106,
      "Plus": 64,
      "PlusMinusPoints": 29,
      "Points": 5,
      "PointsFastBreak": 0,
      "PointsInThePaint": 2,
      "PointsInThePaintAttempted": 3,
      "PointsInThePaintMade": 1,
      "PointsInThePaintPercentage": 33.3333333333333,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 5,
      "ReboundsDefensivePercentage": 29.1485407612992,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 15.7248706738588,
      "ReboundsTotal": 5,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 3,
      "ThreePointersMade": 1,
      "ThreePointersPercentage": 33.3333333333333,
      "TrueShootingAttempts": 6,
      "TrueShootingPercentage": 41.6666666666667,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 3,
      "TwoPointersMade": 1,
      "TwoPointersPercentage": 33.3333333333333,
      "hasPlayed": true,
      "isOnCourt": true,
      "isStarter": true,
      "order": 4,
      "pid": 1630581,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1630598": {
      "Assists": 2,
      "AssistsTurnoverRatio": 2,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": 119.63465638038,
      "Efficiency": "",
      "EfficiencyGameScore": 3,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 4,
      "FieldGoalsEffectivePercentage": 62.5,
      "FieldGoalsMade": 2,
      "FieldGoalsPercentage": 50,
      "FoulsDrawn": 0,
      "FoulsOffensive": 1,
      "FoulsPersonal": 1,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 55,
      "Minutes": "PT16M28.93S",
      "MinutesCalculated": "PT16M",
      "OffensiveRating": 107.615531725605,
      "Plus": 33,
      "PlusMinusPoints": -22,
      "Points": 5,
      "PointsFastBreak": 0,
      "PointsInThePaint": 2,
      "PointsInThePaintAttempted": 1,
      "PointsInThePaintMade": 1,
      "PointsInThePaintPercentage": 100,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 2,
      "ThreePointersMade": 1,
      "ThreePointersPercentage": 50,
      "TrueShootingAttempts": 4,
      "TrueShootingPercentage": 62.5,
      "Turnovers": 1,
      "TurnoversPercentage": 20,
      "TwoPointersAttempted": 2,
      "TwoPointersMade": 1,
      "TwoPointersPercentage": 50,
      "hasPlayed": true,
      "isOnCourt": false,
      "isStarter": false,
      "order": 9,
      "pid": 1630598,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1630846": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 13,
      "pid": 1630846,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1631096": {
      "Assists": 2,
      "AssistsTurnoverRatio": 1,
      "Blocks": 4,
      "BlocksReceived": 1,
      "DefensiveRating": 102.024803357766,
      "Efficiency": "",
      "EfficiencyGameScore": 14.3,
      "FastBreakPointsAttempted": 1,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 9,
      "FieldGoalsEffectivePercentage": 55.5555555555556,
      "FieldGoalsMade": 5,
      "FieldGoalsPercentage": 55.5555555555556,
      "FoulsDrawn": 3,
      "FoulsOffensive": 0,
      "FoulsPersonal": 3,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 4,
      "FreeThrowsMade": 4,
      "FreeThrowsPercentage": 100,
      "Minus": 58,
      "Minutes": "PT30M44.00S",
      "MinutesCalculated": "PT31M",
      "OffensiveRating": 118.105474894719,
      "Plus": 80,
      "PlusMinusPoints": 22,
      "Points": 14,
      "PointsFastBreak": 0,
      "PointsInThePaint": 8,
      "PointsInThePaintAttempted": 6,
      "PointsInThePaintMade": 4,
      "PointsInThePaintPercentage": 66.6666666666666,
      "PointsSecondChance": 2,
      "ReboundsDefensive": 3,
      "ReboundsDefensivePercentage": 11.4279667742448,
      "ReboundsOffensive": 1,
      "ReboundsOffensivePercentage": 4.46234893089557,
      "ReboundsPercentage": 8.22011645164973,
      "ReboundsTotal": 4,
      "SecondChancePointsAttempted": 2,
      "SecondChancePointsMade": 1,
      "SecondChancePointsPercentage": 50,
      "Steals": 2,
      "StealsPercentage": 3.01161227499701,
      "ThreePointersAttempted": 2,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 10.76,
      "TrueShootingPercentage": 65.0557620817844,
      "Turnovers": 2,
      "TurnoversPercentage": 15.6739811912226,
      "TwoPointersAttempted": 7,
      "TwoPointersMade": 5,
      "TwoPointersPercentage": 71.4285714285714,
      "hasPlayed": true,
      "isOnCourt": true,
      "isStarter": true,
      "order": 3,
      "pid": 1631096,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1631099": {
      "Assists": 3,
      "AssistsTurnoverRatio": 3,
      "Blocks": 2,
      "BlocksReceived": 1,
      "DefensiveRating": 120.392607855666,
      "Efficiency": "",
      "EfficiencyGameScore": 14.3,
      "FastBreakPointsAttempted": 1,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 12,
      "FieldGoalsEffectivePercentage": 54.1666666666667,
      "FieldGoalsMade": 6,
      "FieldGoalsPercentage": 50,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 97,
      "Minutes": "PT33M52.00S",
      "MinutesCalculated": "PT34M",
      "OffensiveRating": 115.194462729358,
      "Plus": 80,
      "PlusMinusPoints": -17,
      "Points": 13,
      "PointsFastBreak": 0,
      "PointsInThePaint": 8,
      "PointsInThePaintAttempted": 4,
      "PointsInThePaintMade": 4,
      "PointsInThePaintPercentage": 100,
      "PointsSecondChance": 2,
      "ReboundsDefensive": 8,
      "ReboundsDefensivePercentage": 32.3959505061867,
      "ReboundsOffensive": 2,
      "ReboundsOffensivePercentage": 6.91376992510082,
      "ReboundsPercentage": 18.6489846663904,
      "ReboundsTotal": 10,
      "SecondChancePointsAttempted": 1,
      "SecondChancePointsMade": 1,
      "SecondChancePointsPercentage": 100,
      "Steals": 1,
      "StealsPercentage": 1.37764661221391,
      "ThreePointersAttempted": 6,
      "ThreePointersMade": 1,
      "ThreePointersPercentage": 16.6666666666667,
      "TrueShootingAttempts": 12,
      "TrueShootingPercentage": 54.1666666666667,
      "Turnovers": 1,
      "TurnoversPercentage": 7.69230769230769,
      "TwoPointersAttempted": 6,
      "TwoPointersMade": 5,
      "TwoPointersPercentage": 83.3333333333334,
      "hasPlayed": true,
      "isOnCourt": true,
      "isStarter": true,
      "order": 1,
      "pid": 1631099,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1631114": {
      "Assists": 9,
      "AssistsTurnoverRatio": 4.5,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": 114.369413159185,
      "Efficiency": "",
      "EfficiencyGameScore": 29.1,
      "FastBreakPointsAttempted": 1,
      "FastBreakPointsMade": 1,
      "FastBreakPointsPercentage": 100,
      "FieldGoalsAttempted": 20,
      "FieldGoalsEffectivePercentage": 70,
      "FieldGoalsMade": 13,
      "FieldGoalsPercentage": 65,
      "FoulsDrawn": 2,
      "FoulsOffensive": 0,
      "FoulsPersonal": 3,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 4,
      "FreeThrowsMade": 4,
      "FreeThrowsPercentage": 100,
      "Minus": 75,
      "Minutes": "PT36M45.00S",
      "MinutesCalculated": "PT37M",
      "OffensiveRating": 144.291620239397,
      "Plus": 101,
      "PlusMinusPoints": 26,
      "Points": 32,
      "PointsFastBreak": 4,
      "PointsInThePaint": 20,
      "PointsInThePaintAttempted": 15,
      "PointsInThePaintMade": 10,
      "PointsInThePaintPercentage": 66.6666666666666,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 7,
      "ReboundsDefensivePercentage": 22.2996515679443,
      "ReboundsOffensive": 1,
      "ReboundsOffensivePercentage": 3.73177842565598,
      "ReboundsPercentage": 13.7486573576799,
      "ReboundsTotal": 8,
      "SecondChancePointsAttempted": 1,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 4,
      "ThreePointersMade": 2,
      "ThreePointersPercentage": 50,
      "TrueShootingAttempts": 21.76,
      "TrueShootingPercentage": 73.5294117647059,
      "Turnovers": 2,
      "TurnoversPercentage": 8.41750841750842,
      "TwoPointersAttempted": 16,
      "TwoPointersMade": 11,
      "TwoPointersPercentage": 68.75,
      "hasPlayed": true,
      "isOnCourt": true,
      "isStarter": true,
      "order": 2,
      "pid": 1631114,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1631119": {
      "Assists": 2,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 1,
      "DefensiveRating": 118.278065303764,
      "Efficiency": "",
      "EfficiencyGameScore": 3.4,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 3,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 4,
      "FoulsOffensive": 0,
      "FoulsPersonal": 2,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 6,
      "FreeThrowsMade": 5,
      "FreeThrowsPercentage": 83.3333333333334,
      "Minus": 70,
      "Minutes": "PT21M42.07S",
      "MinutesCalculated": "PT22M",
      "OffensiveRating": 113.508160678738,
      "Plus": 57,
      "PlusMinusPoints": -13,
      "Points": 5,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 1,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 3,
      "ReboundsDefensive": 1,
      "ReboundsDefensivePercentage": 5.39478694993544,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 2.91034559141254,
      "ReboundsTotal": 1,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 1,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 5.64,
      "TrueShootingPercentage": 44.3262411347518,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 2,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": true,
      "isOnCourt": false,
      "isStarter": false,
      "order": 7,
      "pid": 1631119,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1631165": {
      "Assists": 1,
      "AssistsTurnoverRatio": 0,
      "Blocks": 1,
      "BlocksReceived": 0,
      "DefensiveRating": 125.374840578477,
      "Efficiency": "",
      "EfficiencyGameScore": 2.7,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 4,
      "FieldGoalsEffectivePercentage": 62.5,
      "FieldGoalsMade": 2,
      "FieldGoalsPercentage": 50,
      "FoulsDrawn": 1,
      "FoulsOffensive": 0,
      "FoulsPersonal": 5,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 37,
      "Minutes": "PT17M20.93S",
      "MinutesCalculated": "PT17M",
      "OffensiveRating": 132.198981855755,
      "Plus": 37,
      "PlusMinusPoints": 0,
      "Points": 5,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 1,
      "ReboundsDefensivePercentage": 7.90501900086598,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 3.6404692767146,
      "ReboundsTotal": 1,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 3,
      "ThreePointersMade": 1,
      "ThreePointersPercentage": 33.3333333333333,
      "TrueShootingAttempts": 4,
      "TrueShootingPercentage": 62.5,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 1,
      "TwoPointersMade": 1,
      "TwoPointersPercentage": 100,
      "hasPlayed": true,
      "isOnCourt": true,
      "isStarter": false,
      "order": 9,
      "pid": 1631165,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1631172": {
      "Assists": 1,
      "AssistsTurnoverRatio": 1,
      "Blocks": 1,
      "BlocksReceived": 0,
      "DefensiveRating": 80.5327681461536,
      "Efficiency": "",
      "EfficiencyGameScore": 3.7,
      "FastBreakPointsAttempted": 1,
      "FastBreakPointsMade": 1,
      "FastBreakPointsPercentage": 100,
      "FieldGoalsAttempted": 1,
      "FieldGoalsEffectivePercentage": 100,
      "FieldGoalsMade": 1,
      "FieldGoalsPercentage": 100,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 12,
      "Minutes": "PT05M40.00S",
      "MinutesCalculated": "PT05M",
      "OffensiveRating": 102.786582531885,
      "Plus": 19,
      "PlusMinusPoints": 7,
      "Points": 2,
      "PointsFastBreak": 2,
      "PointsInThePaint": 2,
      "PointsInThePaintAttempted": 1,
      "PointsInThePaintMade": 1,
      "PointsInThePaintPercentage": 100,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 2,
      "ReboundsDefensivePercentage": 41.3199426111908,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 22.2910216718266,
      "ReboundsTotal": 2,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 1,
      "StealsPercentage": 8.16678387513895,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 1,
      "TrueShootingPercentage": 100,
      "Turnovers": 1,
      "TurnoversPercentage": 50,
      "TwoPointersAttempted": 1,
      "TwoPointersMade": 1,
      "TwoPointersPercentage": 100,
      "hasPlayed": true,
      "isOnCourt": false,
      "isStarter": false,
      "order": 10,
      "pid": 1631172,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1641717": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": 119.824836260939,
      "Efficiency": "",
      "EfficiencyGameScore": -2.1,
      "FastBreakPointsAttempted": 1,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 3,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 31,
      "Minutes": "PT09M56.00S",
      "MinutesCalculated": "PT10M",
      "OffensiveRating": 0,
      "Plus": 18,
      "PlusMinusPoints": -13,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 3,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 3,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": true,
      "isOnCourt": false,
      "isStarter": false,
      "order": 6,
      "pid": 1641717,
      "status": "ACTIVE",
      "tid": 1610612760
    },
    "1641732": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 13,
      "pid": 1641732,
      "status": "ACTIVE",
      "tid": 1610612758
    },
    "1641749": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 17,
      "pid": 1641749,
      "status": "INACTIVE",
      "tid": 1610612760
    },
    "1641771": {
      "Assists": 0,
      "AssistsTurnoverRatio": 0,
      "Blocks": 0,
      "BlocksReceived": 0,
      "DefensiveRating": "",
      "Efficiency": "",
      "EfficiencyGameScore": 0,
      "FastBreakPointsAttempted": 0,
      "FastBreakPointsMade": 0,
      "FastBreakPointsPercentage": 0,
      "FieldGoalsAttempted": 0,
      "FieldGoalsEffectivePercentage": 0,
      "FieldGoalsMade": 0,
      "FieldGoalsPercentage": 0,
      "FoulsDrawn": 0,
      "FoulsOffensive": 0,
      "FoulsPersonal": 0,
      "FoulsTechnical": 0,
      "FreeThrowsAttempted": 0,
      "FreeThrowsMade": 0,
      "FreeThrowsPercentage": 0,
      "Minus": 0,
      "Minutes": "PT00M00.00S",
      "MinutesCalculated": "PT00M",
      "OffensiveRating": "",
      "Plus": 0,
      "PlusMinusPoints": 0,
      "Points": 0,
      "PointsFastBreak": 0,
      "PointsInThePaint": 0,
      "PointsInThePaintAttempted": 0,
      "PointsInThePaintMade": 0,
      "PointsInThePaintPercentage": 0,
      "PointsSecondChance": 0,
      "ReboundsDefensive": 0,
      "ReboundsDefensivePercentage": 0,
      "ReboundsOffensive": 0,
      "ReboundsOffensivePercentage": 0,
      "ReboundsPercentage": 0,
      "ReboundsTotal": 0,
      "SecondChancePointsAttempted": 0,
      "SecondChancePointsMade": 0,
      "SecondChancePointsPercentage": 0,
      "Steals": 0,
      "StealsPercentage": 0,
      "ThreePointersAttempted": 0,
      "ThreePointersMade": 0,
      "ThreePointersPercentage": 0,
      "TrueShootingAttempts": 0,
      "TrueShootingPercentage": 0,
      "Turnovers": 0,
      "TurnoversPercentage": 0,
      "TwoPointersAttempted": 0,
      "TwoPointersMade": 0,
      "TwoPointersPercentage": 0,
      "hasPlayed": false,
      "isOnCourt": false,
      "isStarter": false,
      "order": 17,
      "pid": 1641771,
      "status": "INACTIVE",
      "tid": 1610612758
    }
  },
  "vtm": {
    "Assists": 32,
    "AssistsTurnoverRatio": 1.77777777777778,
    "BenchPoints": 46,
    "BiggestLead": 4,
    "BiggestLeadScore": "4-0",
    "BiggestScoringRun": 16,
    "BiggestScoringRunScore": "66-88",
    "Blocks": 5,
    "BlocksReceived": 9,
    "DefensivePointsPerPossession": 1.23444790046656,
    "DefensiveRating": 123.444790046656,
    "Efficiency": "",
    "FastBreakPointsAttempted": 6,
    "FastBreakPointsMade": 5,
    "FastBreakPointsPercentage": 83.3333333333334,
    "FieldGoalsAttempted": 90,
    "FieldGoalsEffectiveAdjusted": 0.577777777777778,
    "FieldGoalsMade": 44,
    "FieldGoalsPercentage": 48.8888888888889,
    "FoulsDrawn": 17,
    "FoulsOffensive": 3,
    "FoulsPersonal": 22,
    "FoulsTeam": 19,
    "FoulsTeamTechnical": 0,
    "FoulsTechnical": 0,
    "FreeThrowsAttempted": 13,
    "FreeThrowsMade": 9,
    "FreeThrowsPercentage": 69.2307692307692,
    "LeadChanges": 5,
    "Minutes": "PT240M00.00S",
    "MinutesCalculated": "PT240M",
    "OffensivePointsPerPossession": 1.0894716544543,
    "OffensiveRating": 108.94716544543,
    "OppPointsFromTurnovers": 30,
    "Pace": "",
    "Points": 113,
    "PointsAgainst": 127,
    "PointsFastBreak": 12,
    "PointsFromTurnovers": 14,
    "PointsInThePaint": 44,
    "PointsInThePaintAttempted": 39,
    "PointsInThePaintMade": 22,
    "PointsInThePaintPercentage": 56.4102564102564,
    "PointsSecondChance": 11,
    "Possessions": 103.72,
    "PossessionsOpponent": 102.88,
    "ReboundsDefensive": 30,
    "ReboundsOffensive": 10,
    "ReboundsPersonal": 40,
    "ReboundsTeam": 7,
    "ReboundsTeamDefensive": 0,
    "ReboundsTeamOffensive": 7,
    "ReboundsTotal": 47,
    "SecondChancePointsAttempted": 12,
    "SecondChancePointsMade": 5,
    "SecondChancePointsPercentage": 41.6666666666667,
    "Steals": 5,
    "ThreePointersAttempted": 42,
    "ThreePointersMade": 16,
    "ThreePointersPercentage": 38.0952380952381,
    "TimeLeading": "PT02M08.00S",
    "TimesTied": 4,
    "TransitionDefence": "",
    "TransitionOffence": "",
    "TrueShootingAttempts": 95.72,
    "TrueShootingPercentage": 59.0263267864605,
    "Turnovers": 18,
    "TurnoversTeam": 0,
    "TurnoversTotal": 18,
    "TwoPointersAttempted": 48,
    "TwoPointersMade": 28,
    "TwoPointersPercentage": 58.3333333333333,
    "challengesRemaining": 0,
    "fouls": 5,
    "foulsToGive": 0,
    "isBonus": false,
    "toRemaining": 1
  }
});

        let start = Instant::now();
        for i in 0..1000 {
            encode(&object);
        }
        let duration = start.elapsed();

        println!("Time elapsed in encode(&object) is: {:?}", duration);

    }

}